#+TITLE: Calibration
#+LANGUAGE: en
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage[hmargin=1.5in, vmargin=1in]{geometry}
#+LATEX_HEADER_EXTRA:
#+LATEX_COMPILER: pdflatex

* Overview

The Daya Bay DAQ system produces little more than chunks of timestamped and
digitized electrical signals: We saw a pulse /this/ high, and the peak was
digitized at /this/ instant, and it was part of /this/ trigger block. In order
to carry out any sort of physics analysis with this data, it must first be
converted into more meaningful quantities: How much light did the PMT see? When
did the light arrive on the photocathode? How much energy was deposited in the
scintillator, given the light measurement? This conversion from raw to
calibrated data is the subject of this chapter.

To begin with, the calibration process can be broken down into three different
domains: Timing, charge (gain), and energy (light yield). Properly-calibrated
times are important for time-based vertex reconstruction, while the gain and
light yield calibrations are critical for estimating the desposited energy of an
event. All analyses employ the same timing and gain calibrations, but there
exist multiple independent energy reconstructions, and each uses its own light
yield calibration. We now describe these three calibrations in detail.

The timing calibration converts each hit's TDC count into the more meaningful
quantity of /time since beginning of trigger/, with an additional correction for
the so-called /timewalk effect/, in which smaller pulses cross the
discriminator's threshold.
