#+TITLE: Calibration
#+LANGUAGE: en
#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:nil e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage[hmargin=1.5in, vmargin=1in]{geometry}
#+LATEX_HEADER_EXTRA:
#+LATEX_COMPILER: pdflatex

* Overview

The Daya Bay DAQ system produces little more than chunks of timestamped and
digitized electrical signals: "We saw a pulse /this/ high, and the peak was
digitized at /this/ instant, and it was part of /this/ trigger block." In order
to carry out any sort of physics analysis with this data, it must first be
converted into more meaningful quantities: How much light did the PMT see? When
did the light arrive on the photocathode? How much energy was deposited in the
scintillator, given the light measurement? This conversion from raw to
calibrated data is the subject of this chapter.

To begin with, the calibration process can be broken down into three different
domains: Timing, charge (gain), and energy (light yield). Properly-calibrated
times are important for time-based vertex reconstruction, while the gain and
light yield calibrations are critical for estimating the desposited energy of an
event. All analyses employ the same timing and gain calibrations, but there
exist multiple independent energy reconstructions, and each uses its own light
yield calibration. We now describe these three calibrations in detail.

** Timing calibration

The timing calibration converts each hit's TDC count into the more meaningful
quantity of /time since beginning of trigger/. This involves subtracting out a
channel-specific offset (corresponding to cable length, etc.) with an additional
correction for the so-called /timewalk effect/, in which smaller pulses take
longer to cross the discriminator's threshold. In addition to their application
to time-based vertex reconstructions, these calibrated times are also used in
defining the time window for hit selection (performed during the charge
calculation, described later).[fn::Given that this window is 400\nbsp{}ns wide,
and the timewalk correction is on the order of a few\nbsp{}ns, the raw times
would actually work fine for hit selection.]

*** Calibration constant preparation

In order to correct for each channel's offset and timewalk, they must first be
measured. This requires a well-defined event vertex and an external source of
$T_0$ information.[fn::There is a natural variance in the timing of readout
triggers, smearing the TDC measurements. With knowledge of $T_0$, each event's
trigger jitter can be subtracted from the TDCs of all channels, removing this
smearing. Measuring the channel-by-channel timing behavior would be impossible
without this extra information.] Specifically, Daya Bay uses LED calibration
runs in which the LED is positioned at the center of the detector. When a pulse
arrives at the LED, a "hit" is sent to the FEE from a "fake" $T_0$ channel
(board 18, connector 16). For each PMT hit, we take the TDC, subtract the TDC of
the T0 channel, convert to nanoseconds (using the known TDC frequency), and then
finally subtract the time of flight from the detector center. This gives the
"measured time" of each channel in each event.

In the next step, a 2D histogram is constructed for each channel by taking all
of the channel's hits, across all events, and plotting each hit's "measured
time" $t$ against its ADC count $q$ (on the horizontal axis). This histogram's
profile is then fit to the six-parameter functional form

\[ f(q) = a_1 + a_2 \exp (-a_3 q) + a_4 \exp (-a_5 q) + a_6 \log q, \] 

\noindent which was empirically found to produce good fits when the parameters
were appropriately restricted. After a manual verification of fit quality, the
six parameters for each channel are uploaded to the offline DB, marked with a
suitable validity period. This procedure is repeated whenever the electronics
have been modified in a way that can affect the timing (such as a cabling change
or board replacement).

#+BEGIN_comment
Show the tof-corrected times; comment on TDC discretization. Also, what about
the global offset adjustment? (It's in the DB filler script?) And the fact that
TDC values must be negated.
#+END_comment

*** Hit time correction

Once valid calibration parameters are available in the database, it is a
straightforward process to calibrate the raw data. For each hit, we take the raw
ADC value $q$ and the TDC count $T$, convert $T$ to nanoseconds $t$ using the
TDC frequency, and finally subtract $f(q)$ from $t$. This value is stored in the
calibrated readout structure and is used as the "official" time in all
subsequent analyses.

** Gain calibration

